### ISSUE TITLE
FileServer.h --> not showing right path to images

### ISSUE THREAD

**Issue by dirkclemens** [eloquentarduino/EloquentSurveillance#1]
Great library! Thanks !

I found one error in file:  FileServer.h
`line 60:                html += F("</td><td><a href=\"/view");`
should end with an / after view/ 
`line 60:                html += F("</td><td><a href=\"/view/");`

and 
`line 63:                 html += filename.substring(0);`
instead of filename.substring(1)

**Comment by Patriboom** [comment]
I don't use the same version as you. Do I ? 
Around those lines, my FileServer.h file looks like:
```
		                    _server.sendContent(F(">"));
		                    _server.sendContent(F("<td>"));
		                    _server.sendContent(String(i++));
		                    _server.sendContent(F("</td><td><a href=\"/view"));
		                    _server.sendContent(filename);
		                    _server.sendContent(F("\" style=\"font-weight: bold;\" target=\"_blank\">"));
		                    _server.sendContent(filename.substring(1));
		                    _server.sendContent(F("</a></td><td>"));
		                    _server.sendContent(formatBytes(file.size()));
		                    _server.sendContent(F("</td><td>"));
		                    _server.sendContent(F("<a href=\"/delete"));
		                    _server.sendContent(filename);
		                    _server.sendContent(F("\" style=\"color: #600; font-weight: bold;\" >X</a>"));
		                    _server.sendContent(F("</td></tr>"));

```
I can find no « html += " expression.
About the misstyping you quote on line 60, your correction is useless for my code.  The code I downloaded is like the one you pretend wrong but works good for me.

**Comment by ghmpi** [comment]
Something that may be related..
I tried 1.0.13 and things were not happy with the new rotate code.. on Chrome browser the image would not display.

1.0.12 works fine. I did notice the change in the code for the "/view" vs "/view/" portion. Something changed and it's not happy, at least for me.

**Comment by Patriboom** [comment]
I would like to help.
Where do you find the version's number ?   (   1.0.13   / 1.0.12 ) ?

**Comment by ghmpi** [comment]
Is the original author not working on this anymore?

**Comment by Patriboom** [comment]
I'm not sure, but when I wrote him a personnal message he invited me to adopt the new library.  I wrote him one month ago a message about some modifications I suggested for the FileServer.h file.  And until then, my modifications are waiting (see « pull requests » ) .... so is my conclusion (from what He wrote me and from the long delay to accept the pull request).

**Comment by ghmpi** [comment]
Thank you Patriboom for your comments.
I was looking for motion detection code for the ESP32 camera.. and came across this. Now I see the other libraries from the same author.. but it seems to be similar to this one with additions maybe? I have to look into them when I have time.

This library itself is not so big, so I can usually find and fix bugs myself, but it takes time. I would, obviously, rather everything work correctly. 

It would be good to know that the original author has moved on to something else and is not maintaining this code, if this is indeed the case.

Thank you all!

**Comment by Patriboom** [comment]
Hello Ghmpi, 
I' surprised to read that the code doesn't work.  On my ESP32-cam mvt dectector works good.  I merged it with an FTP file server.  Do you use Windows / Mac / other or Liinux ? 
My code reads also config from microSD and write pictures on the same card.  An other code of mvt dectector sends email on every detection.

**Comment by ghmpi** [comment]
I tried your suggestions by including the two brownout include files, and the brownout disable line.. still the same thing. I don't believe the device is browning out.

I tried windows 7, and windows 10, Chrome brower on each, plus an android device. Also tried an old version of Internet Explorer and a new version of edge. The newest 1.0.13 rotate code just does not seem to work.

Also, in the main http page where the device lists the jpegs, I get "apture.jpg" instead of "capture.jpg"... this was also reported by someone else as a bug.

I can't put more time into this right now.. this project was just for fun. I'll do some more research in the future, maybe I'll look at your fork or revisit this again as well.

Thank you for your time.

Regards,
-Moses

**Comment by Patriboom** [comment]
Sometime, it is as simple as too long delay for browser.  Just refresh your page and the image may show up.

**Comment by Patriboom** [comment]
Did you find an answer ? 
Finally, on a forth aithinker ESP32cam, I encounter the same problem as you and can not solve it.
